// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import Navbar from "@/components/layout/Navbar";
// import Footer from "@/components/layout/Footer";
// import WhatsAppButton from "@/components/whatsap/WhatsAppButton";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />
//         {children}
//         <WhatsAppButton />
//         {/* <WhatsAppButton /> */}
//         <Footer />
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import WhatsAppButton from "@/components/whatsap/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kalerwe Parent School - Quality Education for Future Leaders",
  description: "Kalerwe Parent School offers quality education, modern curriculum, and holistic development for students. Join our community dedicated to academic excellence and character building.",
  keywords: "Kalerwe Parent School, education, Kampala schools, primary education, Uganda schools, quality education",
  authors: [{ name: "Kalerwe Parent School" }],
  creator: "Kalerwe Parent School",
  publisher: "Kalerwe Parent School",
  robots: "index, follow",
  openGraph: {
    title: "Kalerwe Parent School - Quality Education for Future Leaders",
    description: "Quality education and holistic development for students in Kampala, Uganda",
    type: "website",
    locale: "en_UG",
    siteName: "Kalerwe Parent School",
  },
  twitter: {
    card: "summary_large_image",
    title: "Kalerwe Parent School - Quality Education for Future Leaders",
    description: "Quality education and holistic development for students in Kampala, Uganda",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <meta name="theme-color" content="#1e40af" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="min-h-screen">
          {children}
        </main>
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}